version: "2"

services:
    redis:
        image: redis:alpine
        container_name: redis
        ports: 
            - 6379:6379
    apigateway:
        build: .
        container_name: "apigateway"
        stdin_open: true
        network_mode: host
        dns:
            - 8.8.8.8
            - 127.0.0.53        
        environment:
            - ENV_USER=usman.tahir@vista.co
            - ENV_PASSWORD=vgpgtp123
        ports:
            - 5000:5000/tcp
        depends_on:
            - redis
